keycloak:

  # Image
  image: 
    tag: 21.1.2-debian-11-r1

  # Logging
  logging:
    level: INFO

  # Replica
  replicaCount: 1

  # Admin account
  auth:
    adminUser: fiwareAdmin
    adminPassword: fiwareAdmin

  # CLI config
  keycloakConfigCli:
    enabled: true
    # current image does not contain 20.0.3., thus we need this fix
    command: 
      - java
      - -jar
      - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-20.0.1.jar

    extraEnvVars:
      - name: IMPORT_FILES_LOCATIONS
        value: "/config/*"
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false

    # Realm config - either provide configuration or existing ConfigMap
    configuration: {}
    existingConfigmap: ""

  # ENVs
  extraEnvVars:
  - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_LOG_LEVEL
    value: INFO
  - name: VCISSUER_ISSUER_DID
    value: "did:web:my-did:did"
  - name: VCISSUER_WALTID_ADDRESS
    value: "http://vcwaltid"

  # Volume mounts
  extraVolumeMounts:
    - name: profiles
      mountPath: /opt/bitnami/keycloak/conf/profile.properties
      subPath: profile.properties
    - name: providers
      mountPath: /opt/bitnami/keycloak/providers/
    - name: data
      mountPath: /data

  # Volumes
  extraVolumes:
    - name: data
      emptyDir: {}
    - name: profiles
      configMap:
        name: keycloak-profile
    - name: providers
      emptyDir: {}
    - name: did-config
      configMap:
        name: keycloak-did-config
    - name: did-secret
      secret: 
        secretName: vcwaltid-tls-sec

  # Init containers for VC issuer and loading of DID
  initContainers:
    - name: add-vc-issuer
      image: quay.io/fiware/keycloak-vc-issuer:1.0.1
      imagePullPolicy: Always
      volumeMounts:
        - name: providers
          mountPath: /target
    - name: load-did
      image: quay.io/opencloudio/curl:4.2.0-build.8
      imagePullPolicy: Always
      command: 
        - /bin/sh
        - /opt/did/script/import.sh
      env:
        - name: WALTID_CORE_ADDRESS
          value: "vcwaltid:7000"
      volumeMounts:
        - name: did-config
          mountPath: /opt/did/script
        - name: did-secret
          mountPath: /opt/did/secret

  # Disable internal DB
  postgresql:
    enabled: false

  # Config for external DB
  externalDatabase:
    host: postgresql
    user: keycloak
    password: "<keycloak-password>"
    database: keycloak

# Config to create DID
didConfig:
  # Enable creation of ConfigMap for loading the DID into walt-id
  # When disabling, also remove the load-did initContainer from the list above
  loadDidWebEnabled: true

  # Domain for DID web
  domain: "provider.com"

  # x5u for DID web
  x5u: "https://provider.com/certs/tls.crt"

# OpenShift Route config
route:
  enabled: false
  host: my-host.org
  tls: {}
  certificate: {}
