tm-forum-api:
  ## configuration to be used by every api-deployment if nothing specific is provided.
  defaultConfig:
  
    # -- configuration to be used for the image of the container
    image:
      # -- repository to get the container from
      #repository: quay.io/wi_stefan
      repository: quay.io/beknazar
      # -- tag to be used, most of the time the apis will use the same version
      #tag: 0.5.0
      tag: 2.0.6
      # -- pull policy to be used
      pullPolicy: IfNotPresent

    # --  ngsi-ld broker connection information
    ngsiLd:
      # -- timeout for requests ot the broker
      readTimeout: 30s
      # -- base path for the ngsi-ld api
      path: ngsi-ld/v1
      # -- address of the broker
      url: http://orion:1026

  # enable the api proxy
  apiProxy:
    image:
      tag: distroless-v1.27-latest
    enabled: true
    service: 
      nameOverride: pdc-tmforum-api

  # -- list of apis to be deployed
  # -- every api needs to define a name and image. Basepath is required when routes or ingress will be enabled. Beside that, they can overwrite the default-config by using the same keys.
  # -- be aware: when you change the image repositrory or the tag for an api, you have to provide both values for the changes to take effect
  apis:
    - name: party-catalog
      image: tmforum-party-catalog
      basePath: /tmf-api/party/v4
      
    - name: customer-bill-management
      image: tmforum-customer-bill-management
      basePath: /tmf-api/customerBillManagement/v4
      
    - name: customer-management
      image: tmforum-customer-management
      basePath: /tmf-api/customerManagement/v4
      
    - name: product-catalog
      image: tmforum-product-catalog
      basePath: /tmf-api/productCatalogManagement/v4
      
    - name: product-inventory
      image: tmforum-product-inventory
      basePath: /tmf-api/productInventory/v4
      
    - name: product-ordering-management
      image: tmforum-product-ordering-management
      basePath: /tmf-api/productOrderingManagement/v4
      
    - name: resource-catalog
      image: tmforum-resource-catalog
      basePath: /tmf-api/resourceCatalog/v4
      
    - name: resource-function-activation
      image: tmforum-resource-function-activation
      basePath: /tmf-api/resourceFunctionActivation/v4
      
    - name: resource-inventory
      image: tmforum-resource-inventory
      basePath: /tmf-api/resourceInventoryManagement/v4
      
    - name: service-catalog
      image: tmforum-service-catalog
      basePath: /tmf-api/serviceCatalogManagement/v4
