tm-forum-api:
  ## configuration to be used by every api-deployment if nothing specific is provided.
  defaultConfig:
  
    # -- configuration to be used for the image of the container
    image:
      # -- repository to get the container from
      repository: quay.io/wi_stefan
      # -- tag to be used, most of the time the apis will use the same version
      tag: 0.5.0
      # -- pull policy to be used
      pullPolicy: IfNotPresent

    # --  ngsi-ld broker connection information
    ngsiLd:
      # -- timeout for requests ot the broker
      readTimeout: 30s
      # -- base path for the ngsi-ld api
      path: ngsi-ld/v1
      # -- address of the broker
      url: http://orion:1026

  # -- list of apis to be deployed
  # -- every api needs to define a name and image. Basepath is required when routes or ingress will be enabled. Beside that, they can overwrite the default-config by using the same keys.
  # -- be aware: when you change the image repositrory or the tag for an api, you have to provide both values for the changes to take effect
  apis:
    - name: party-catalog
      image: tmforum-party-catalog
      basePath: /tmf-api/party/v4
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF632-Party-v4.0.0.swagger.json

    - name: customer-bill-management
      image: tmforum-customer-bill-management
      basePath: /tmf-api/customerBillManagement/v4
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF678-CustomerBill-v4.0.0.swagger.json

    - name: customer-management
      image: tmforum-customer-management
      basePath: /tmf-api/customerManagement/v4
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF629-Customer-v4.0.0.swagger.json

    - name: product-catalog
      image: tmforum-product-catalog
      basePath: /tmf-api/productCatalogManagement/v4
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF620-ProductCatalog-v4.1.0.swagger.json

    - name: product-inventory
      image: tmforum-product-inventory
      basePath: /tmf-api/productInventory/v4
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF637-ProductInventory-v4.0.0.swagger.json

    - name: product-ordering-management
      image: tmforum-product-ordering-management
      basePath: /tmf-api/productOrderingManagement/v4
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF622-ProductOrder-v4.0.0.swagger.json

    - name: resource-catalog
      image: tmforum-resource-catalog
      basePath: /tmf-api/resourceCatalog/v4
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.1.0/swagger/TMF634-ResourceCatalog-v4.0.0.swagger.json

    - name: resource-function-activation
      image: tmforum-resource-function-activation
      basePath: /tmf-api/resourceFunctionActivation/v4
      specUrl: https://raw.githubusercontent.com/wistefan/TMF664_ResourceFunctionActivationConfiguration/master/TMF664-ResourceFunctionActivation-v4.0.0.swagger.json

    - name: resource-inventory
      image: tmforum-resource-inventory
      basePath: /tmf-api/resourceInventoryManagement/v4
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF639-ResourceInventory-v4.0.0.swagger.json

    - name: service-catalog
      image: tmforum-service-catalog
      basePath: /tmf-api/serviceCatalogManagement/v4
      specUrl: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/4.0.0/swagger/TMF633-ServiceCatalog-v4.0.0.swagger.json
