activation-service:
  deployment:
    image:
      repository: quay.io/i4trust/activation-service
      tag: 2.2.1
      pullPolicy: IfNotPresent

  ## Configuration of activation service execution
  activationService:
    # -- Listen port
    port: 8080
    # -- Number of (gunicorn) workers that should be created
    workers: 1
    # -- Maximum header size in bytes
    maxHeaderSize: 32768
    # -- Log Level
    logLevel: "debug"

  ## CCS config
  ccs:
    endpoint: "http://ccs-credentials-config-service:8080/"
    id: "my-activation-service"
    defaultOidcScope: "default"
    oidcScopes:
      default:
        - type: "VerifiableCredential"
          trustedParticipantsLists: [
            "https://tir.dataspace.com"
          ]
          trustedIssuersLists: [
            "http://til-trusted-issuers-list:8080"
          ]
        - type: "ActivationService"
          trustedParticipantsLists: [
            "https://tir.dataspace.com"
          ]
          trustedIssuersLists: [
            "http://til-trusted-issuers-list:8080"
          ]

  ## AS config
  config:

    # DB
    db:
      # -- Use sqlite in-memory database
      useMemory: true
      # -- Enable tracking of modifications
      modTracking: false
      # -- Enable SQL logging to stderr
      echo: true

    # Configuration for additional API keys to protect certain endpoints
    apikeys:
      # Config for iSHARE flow
      ishare:
        # Enable for /token endpoint (API key will be required)
        enabledToken: false
        # Enable for /createpolicy endpoint (API key will be required)
        enabledCreatePolicy: false
      # Config for Trusted-Issuers-List flow
      issuer:
        # Header name
        headerName: "AS-API-KEY"
        # API key (auto-generated if left empty)
        apiKey: ""
        # Enable for /issuer endpoint (API key will be required)
        enabledIssuer: true
      
    ar:
      # Endpoint for token request
      token: "https://ar.isharetest.net/connect/token"
      # Endpoint for create policy requests
      policy: "https://ar.isharetest.net/policy"
      # Endpoint for delegation requests
      delegation: "https://ar.isharetest.net/delegation"
      # EORI of AR
      id: "EU.EORI.DEPROVIDER"

    issuer:
      clientId: "my-activation-service"
      providerId: "did:web:my-did:did"
      tilUri: "http://til-trusted-issuers-list:8080"
      verifierUri: "https://verifier.provider.com"
      samedevicePath: "/api/v1/samedevice"
      jwksPath: "/.well-known/jwks"
      algorithms:
        - "ES256"
      roles:
        createRole: "CREATE_ISSUER"
        updateRole: "UPDATE_ISSUER"
        deleteRole: "DELETE_ISSUER"
