dsba-pdp:

  # DB
  db: 
    enabled: false
    migrate:
      enabled: false

  deployment:
    # Image
    image:  
      pullPolicy: Always
      repository: quay.io/fiware/dsba-pdp 
      tag: 1.0.0

    # Log level
    logLevel: TRACE

    # iSHARE config
    ishare:
      existingSecret: vcwaltid-tls-sec

      clientId: did:web:my-did:did
      trustedFingerprints:
        - MYFINGERPRINT

      ar:
        id: "did:web:my-did:did"
        delegationPath: "/ar/delegation"
        tokenPath: "/oauth2/token"
        url: "https://ar.provider.com"

      trustAnchor:
        id: "EU.EORI.FIWARESATELLITE"
        tokenPath: "/token"
        trustedListPath: "/trusted_list"
        url: "https://tir.dataspace.com"

    # Verifier
    trustedVerifiers:
      - https://verifier.provider.com/.well-known/jwks

    # Provider DID
    providerId: "did:web:my-did:did"

  # ENVs
  additionalEnvVars:
    - name: ISHARE_CERTIFICATE_PATH
      value: /iShare/tls.crt
    - name: ISHARE_KEY_PATH
      value: /iShare/tls.key
