# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

# List of directories to scan for updates
updates:
  - package-ecosystem: "docker"
    directory: "argocd/applications/activation-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "argocd/applications/contract-management"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "argocd/applications/credentials-config-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "argocd/applications/dsba-pdp"
    schedule:
      interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "argocd/applications/keycloak"
  #  schedule:
  #    interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "argocd/applications/keyrock"
  #  schedule:
  #    interval: "daily"
  - package-ecosystem: "docker"
    directory: "argocd/applications/kong"
    schedule:
      interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "argocd/applications/mongodb"
  #  schedule:
  #    interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "argocd/applications/mysql"
  #  schedule:
  #    interval: "daily"
  - package-ecosystem: "docker"
    directory: "argocd/applications/orion-ld"
    schedule:
      interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "argocd/applications/postgres"
  #  schedule:
  #    interval: "daily"
  - package-ecosystem: "docker"
    directory: "argocd/applications/tm-forum-api"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "argocd/applications/trusted-issuers-list"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "argocd/applications/vcwaltid"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "argocd/applications/verifier"
    schedule:
      interval: "daily"
  
