# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "applications/activation-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "applications/contract-management"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "applications/credentials-config-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "applications/dsba-pdp"
    schedule:
      interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "applications/keycloak"
  #  schedule:
  #    interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "applications/keyrock"
  #  schedule:
  #    interval: "daily"
  - package-ecosystem: "docker"
    directory: "applications/kong"
    schedule:
      interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "applications/mongodb"
  #  schedule:
  #    interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "applications/mysql"
  #  schedule:
  #    interval: "daily"
  - package-ecosystem: "docker"
    directory: "applications/orion-ld"
    schedule:
      interval: "daily"
  #- package-ecosystem: "docker"
  #  directory: "applications/postgres"
  #  schedule:
  #    interval: "daily"
  - package-ecosystem: "docker"
    directory: "applications/tm-forum-api"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "applications/trusted-issuers-list"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "applications/vcwaltid"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "applications/verifier"
    schedule:
      interval: "daily"
  
