{{- if .Values.ingress.enabled -}}
{{- $fullName := include "waltid.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "waltid.fullname" . }}
  labels:
    {{ include "waltid.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /v1/did/{{ .Values.did }}
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.class}}
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
        - pathType: Prefix
          path: "/did/did.json"
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: 7000
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ .Values.ingress.host}}
    secretName: {{ include "waltid.fullname" . }}-tls-sec
  {{- end }}
{{- end }}
