apiVersion: v1
kind: Service
metadata:
  name: {{ include "waltid.fullname" . }}-certs
  labels:
    {{ include "waltid.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "waltid.name" . }}-certs
    app.kubernetes.io/instance: {{ .Release.Name }}
