contract-management:
  deployment:
    image:
      repository: quay.io/fiware/contract-management
      # -- tag of the image to be used
      tag: 1.0.0
      pullPolicy: IfNotPresent
  ## Config parameters to be used when adding issuers to TIL
  til: {}
    ## Type of Verifiable Credential necessary for accessing the service
    ##credentialType: MyCredential
    ## Claims with permissions granted to given Verifiable Credential
    ##claims:
      ## DID of the target service that is requiring the permissions
    ##  - target: "did:some:service"
    ##    ## Roles that are added/allowed for the given service
    ##    roles:
    ##      - Consumer
    ##      - Admin
  services:
    ## Config for Trusted Issuers List
    til:
      ## Path to be used
      path: ""
      ## URL of the Trusted Issuers List Service
      url: http://${til-service}:8080
      ## Read timeout in sec
      read-timeout: 30
    ## Config for the TM Forum Service hosting the Product Ordering API
    product:
      ## Path to be used
      path: "/tmf-api/productOrderingManagement/v4"
      ## URL of the TM Forum Service hosting the Product Ordering API
      url: http://${tm_forum_proxy}:8080
      ## Read timeout in sec
      read-timeout: 30
    ## Config for the TM Forum Service hosting the Party API
    party:
      ## Path to be used
      path: "/tmf-api/party/v4"
      ## URL of the TM Forum Service hosting the Party API
      url: http://${tm_forum_proxy}:8080
      ## Read timeout in sec
      read-timeout: 30 
    
