postgresql:
  
  fullnameOverride: postgresql-dsc
  
  auth:
    # Credentials for Keycloak DB
    username: keycloak
    password: "<keycloak-password>"
    enablePostgresUser: true

    # Credentials for postgres admin user
    postgresPassword: "<admin-password>"
    
  # Init DB
  primary:
    initdb:
      scripts:
        create.sh: |
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE keycloak;"
