apiVersion: v2
name: data-space-connector
description: Helm chart to deploy the FIWARE Data Space Connector
type: application
version: 1.0.0
maintainers:
  - name: Dennis Wendland
    email: dennis.wendland@fiware.org
  - name: Stefan Wiedemann
    email: stefan.wiedemann@fiware.org
dependencies: []