apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-routes
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{ include "authentication.labels" . | nindent 4 }}
data:
  apisix.yaml: |-
    routes:
      - uri: /*
        upstream:
            nodes:
                {{ .Values.apisix.upstream.url}}: 1
            type: roundrobin
        plugins:
          openid-connect:
            client_id: {{ .Values.apisix.oidc.clientId }}
            client_secret: the-secret
            bearer_only: true
            use_jwks: true
            discovery: {{ .Values.apisix.oidc.discoveryEndpoint }}
          opa:
            host: "http://localhost:{{ .Values.opa.port }}"
            policy: policy/main
    #END