{{- if .Values.didConfig.loadDidWebEnabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-did-config
data:
  import.sh: |-
    export KEY=$(cat /opt/did/secret/tls.key)
    export KEY_ID=$(curl --location "${WALTID_CORE_ADDRESS}/v1/key/import" --header 'Content-Type: text/plain' --data "${KEY}" | jq -r '.id')
    echo The key id: ${KEY_ID}
    curl --location "${WALTID_CORE_ADDRESS}/v1/did/create" \
      --header 'Content-Type: application/json' \
      --data "{
          \"method\": \"web\",
          \"keyAlias\":\"${KEY_ID}\",
          \"domain\": \"{{ .Values.didConfig.domain }}\",
          \"path\": \"did\",
          \"x5u\": \"{{ .Values.didConfig.x5u }}\"
      }"
{{- end }}
