orion:
      
  broker:
    db:
      auth: 
        user: root
        password: "<mongodb-password>"
        mech: "SCRAM-SHA-1"
      hosts:
        - mongodb

  mongo:
    # we want to use the individually deployed mongodb
    enabled: false
