apiVersion: v2
name: credentials-config-service
description: Chart holder for argo-cd

type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: credentials-config-service
    version: 0.0.1
    repository: https://fiware.github.io/helm-charts
