mongodb:
  
  auth:
    enabled: true
    rootPassword: "<mongodb-password>"
    
  architecture: standalone
  
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

  resources:
    limits:
      cpu: 200m
      memory: 512Mi

  persistence:
    enabled: true
    size: 8Gi
