trusted-issuers-list:

  # Image
  deployment:
    image:  
      tag: 0.0.3

  # Configure an Ingress or OpenShift Route
  ingress:
    til:
      enabled: false
    tir:
      enabled: false
  route:
    til:
      enabled: false
    tir:
      enabled: false
      
  # Database config
  database:
    persistence: true
    host: mysql-dsc
    name: til

    # Should use Secret in production environment
    username: root
    password: "<mysql-password>"
