apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "waltid.fullname" . }}-certs
  labels:
    app.kubernetes.io/name: {{ include "waltid.name" . }}-certs
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "waltid.name" . }}-certs
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "waltid.name" . }}-certs
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec: 
      serviceAccountName: default
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: Always
          image: "lipanski/docker-static-website:2.1.0"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /home/static/certs
      volumes:
        - name: certs
          secret:
            secretName: {{ include "waltid.fullname" . }}-tls-sec
            items: 
              - key: tls.crt
                path: tls.crt
